export const energy: { [key: string]: number } = {
  grass: 1,
  fire: 2,
  water: 3,
  lightning: 4,
  psychic: 5,
  fighting: 6,
  dark: 7,
  metal: 8,
  fairy: 9,
  dragon: 10,
  colorless: 11,
};

export const rarity: {
  [key: string]: number;
} = {
  common: 1,
  uncommon: 2,
  rare: 3,
  'ace spec rare': 4,
  'amazing rare': 5,
  'classic collection': 6,
  promo: 7,
  'rare holo': 8,
  'rare shiny': 9,
  'shiny rare': 10,
  'double rare': 11,
  legend: 12,
  'radiant rare': 13,
  'rare ace': 14,
  'rare break': 15,
  'rare holo ex': 16,
  'rare holo gx': 17,
  'rare holo lv.x': 18,
  'rare holo star': 19,
  'rare holo v': 20,
  'rare holo vmax': 21,
  'rare holo vstar': 22,
  'rare prime': 23,
  'rare prism star': 24,
  'rare rainbow': 25,
  'rare secret': 26,
  'rare shining': 27,
  'rare shiny gx': 28,
  'rare ultra': 29,
  'shiny ultra rare': 30,
  'ultra rare': 31,
  'illustration rare': 32,
  'special illustration rare': 33,
  'trainer gallery rare holo': 34,
  'hyper rare': 35,
};

export const supertype: { [key: string]: number } = {
  pokémon: 1,
  trainer: 2,
  energy: 3,
};
export const subtype: { [key: string]: number } = {
  basic: 1,
  'stage 1': 2,
  'stage 2': 3,
  baby: 4,
  ancient: 5,
  future: 6,
  break: 7,
  tera: 8,
  'ultra beast': 9,
  legend: 10,
  'level-up': 11,
  radiant: 12,
  prime: 13,
  'prism star': 14,
  'rapid strike': 15,
  restored: 16,
  'single strike': 17,
  sp: 18,
  special: 19,
  'tag team': 20,
  star: 21,
  mega: 22,
  ex: 23,
  gx: 24,
  v: 25,
  eternamax: 26,
  'fusion strike': 27,
  vmax: 28,
  vstar: 29,
  'v-union': 30,
  item: 31,
  'technical machine': 32,
  'goldenrod game corner': 33,
  'pokémon tool': 34,
  "rocket's secret machine": 35,
  'pokémon tool f': 36,
  'ace spec': 37,
  stadium: 38,
  supporter: 39,
  'team plasma': 40,
};
